SKILL_SYNONYMS = {
    "python": ["python", "py"],
    "java": ["java"],
    "javascript": ["javascript", "js"],
    "sql": ["sql", "mysql", "postgresql", "postgres"],
    "tensorflow": ["tensorflow", "tf"],
    "pytorch": ["pytorch", "torch"],
    "opencv": ["opencv"],
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning", "dl"],
    "computer vision": ["computer vision", "cv", "image processing"],
    "nlp": ["nlp", "natural language processing"],
    "generative ai": ["generative ai", "genai"],
    "llm": ["llm", "llms", "large language model", "large language models"],
    "langchain": ["langchain"],
    "langgraph": ["langgraph"],
    "rag": ["rag", "retrieval augmented generation"],
    "fastapi": ["fastapi"],
    "flask": ["flask"],
    "django": ["django"],
    "react": ["react", "reactjs"],
    "next.js": ["next.js", "nextjs"],
    "node.js": ["node.js", "nodejs", "node"],
    "mongodb": ["mongodb", "mongo"],
    "postgresql": ["postgresql", "postgres"],
    "docker": ["docker", "containerization"],
    "kubernetes": ["kubernetes", "k8s"],
    "aws": ["aws", "amazon web services"],
    "azure": ["azure"],
    "gcp": ["gcp", "google cloud"],
    "git": ["git"],
    "github": ["github"],
    "linux": ["linux"],
    "rest api": ["rest api", "rest apis", "backend api", "backend apis", "api development"],
    "streamlit": ["streamlit"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "matplotlib": ["matplotlib"],
    "seaborn": ["seaborn"],
    "transformers": ["transformers", "hugging face transformers"],
    "hugging face": ["hugging face", "huggingface"],
    "faiss": ["faiss"],
    "vector database": ["vector database", "vector db", "chroma", "pinecone", "qdrant", "weaviate"],
    "redis": ["redis"],
    "html": ["html"],
    "css": ["css"],
    "tailwind": ["tailwind", "tailwind css"],
    "data structures": ["data structures", "dsa"],
    "algorithms": ["algorithms", "problem solving"]
}